from application.database_processor import get_all_infor_building, get_building_by_id, get_building_by_name, get_building_by_ward
from application.get_weather import get_the_weather_today
from application.calculate_pit import calculate_pit_in_vn
from application.update_file import create_file